name: GitHub Actions Demo
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
        run: |
          export STAGE=build
          bash ${{ github.workspace }}/run.sh
      - run: echo "?? This job's status is ${{ job.status }}."
  deploy-job:
    runs-on: ubuntu-latest
    steps:
        run: |
          export STAGE=deploy
          bash ${{ github.workspace }}/run.sh
      - run: echo "?? This job's status is ${{ job.status }}."
  publish-job:
    runs-on: ubuntu-latest
    steps:
        run: |
          export STAGE=publish
          bash ${{ github.workspace }}/run.sh
      - run: echo "?? This job's status is ${{ job.status }}."
